Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 8
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	AlignFastq
	1	Sort
	1	all
	3

[Wed Oct  3 15:43:13 2018]
rule AlignFastq:
    input: /scratch/dana/trimmed/1285_covaris2_DNA_200ng_S4_L008_R1_001.fastq.gz, /scratch/dana/trimmed/1285_covaris2_DNA_200ng_S4_L008_R3_001.fastq.gz
    output: /scratch/dana/bam/1285_covaris2_DNA_200ng_S4_L008.bam
    jobid: 8
    wildcards: sample=1285_covaris2_DNA_200ng_S4_L008

[Wed Oct  3 15:43:13 2018]
Error in rule AlignFastq:
    jobid: 8
    output: /scratch/dana/bam/1285_covaris2_DNA_200ng_S4_L008.bam

RuleException:
CalledProcessError in line 34 of /home/dnachman/XTHS-analysis/code/pipeline.smk:
Command ' set -euo pipefail;  bwa mem -t 2 -M -R '@RG	ID:tissue	SM:tissue'/home/dnachman/XTHS-analysis/data/genome/hg19/hg19.fa /scratch/dana/trimmed/1285_covaris2_DNA_200ng_S4_L008_R1_001.fastq.gz /scratch/dana/trimmed/1285_covaris2_DNA_200ng_S4_L008_R3_001.fastq.gz | samtools view -bh - > /scratch/dana/bam/1285_covaris2_DNA_200ng_S4_L008.bam ' returned non-zero exit status 1.
  File "/home/dnachman/XTHS-analysis/code/pipeline.smk", line 34, in __rule_AlignFastq
  File "/home/dnachman/miniconda3/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Removing output files of failed job AlignFastq since they might be corrupted:
/scratch/dana/bam/1285_covaris2_DNA_200ng_S4_L008.bam
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /home/dnachman/XTHS-analysis/code/.snakemake/log/2018-10-03T154313.767048.snakemake.log
